version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./turivius-code-challenge-repo/ :/usr/src/turivius-code-challenge-repo/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev