# Generated by Django 3.1.1 on 2020-09-28 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('court_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lawsuit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_processo', models.CharField(max_length=30, unique=True)),
                ('id_cliente', models.IntegerField()),
                ('favor_contribuinte', models.CharField(choices=[('0', 'Loss'), ('1', 'Share'), ('2', 'Win')], max_length=1)),
                ('ementa', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Lawsuits',
        ),
    ]
