# Generated by Django 3.1.1 on 2020-09-28 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('court_app', '0002_auto_20200928_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawsuit',
            name='ementa',
            field=models.CharField(max_length=500),
        ),
    ]
