# Generated by Django 3.1.1 on 2020-09-28 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('court_app', '0003_auto_20200928_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawsuit',
            name='ementa',
            field=models.TextField(),
        ),
    ]
