# Generated by Django 3.1.1 on 2020-09-28 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('court_app', '0005_process'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Process',
        ),
    ]
