# Generated by Django 3.1.1 on 2020-10-02 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('court_app', '0006_delete_process'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('lawsuit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='court_app.lawsuit')),
            ],
            bases=('court_app.lawsuit',),
        ),
    ]
