# Generated by Django 3.1.1 on 2020-10-05 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('court_app', '0007_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
    ]
